---
title: "CRISPRi_exact_test"
author: ""
date: ""
output: html_document
editor_options: 
  chunk_output_type: console
---


#### NOTE this is a piece of highly customised script, think carefully before chaning anything. 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/")
getwd()
```

```{r load libraries}

packs_required<-c("BiocManager","pacman")
if_insta_packs<-packs_required %in% rownames(installed.packages())
if (any(if_insta_packs == FALSE)) {
  install.packages(packs_required[!if_insta_packs])
  }

# load CRAN and Bioconductor packages
pacman::p_load(tidyverse,readxl,writexl,data.table,edgeR)

```

```{r customised function, include=FALSE}
# DO NOT change anything from this code chunk unless you know exactly what you are doing
run_analysis<-function(select.strain,select.day,select.reference,select.exp.id,outdir){  
  

  reference.sample<-paste0(select.reference,"_",select.strain,"_d",select.day)
  
  # subset data into just one experiment  
  data<-data.all1%>%
    filter(day==select.day & 
           strain==select.strain &
           exp.id==select.exp.id)
  
  data.valid<-data%>%
    filter(exclude==0 )%>% # & !(guide.id%in%guide_removed)
    select(-exclude)
  
  
  data.wide<-data.valid%>%
                mutate(column.name=paste0(sample.name,".strain.",strain,".day.",day,".rep.",replicate))%>%
                select(guide.id,column.name,reads)%>%
                arrange(column.name)%>%
                pivot_wider(names_from=column.name,
                            values_from=reads)%>%#,

                arrange(guide.id)%>%
                ungroup()
     

  data.wide.filtered<-data.wide
  
  
  annotations<-data.wide.filtered%>%select(guide.id)

  reads<-data.wide.filtered%>%select(starts_with("Atc"))

  
  samples<-factor(colnames(reads)%>%str_replace_all(".strain.","_")%>%
                                  str_replace_all(".day.","_d")%>%
                                  str_remove_all(".rep.*"))
  
  # reorder the factors
  samples<-relevel(samples,ref=reference.sample)
  
  # initiate the edgeR object
  dataset<-DGEList(counts=reads,group=samples,genes=annotations)
      
  

  # estimate the dispersion
  dataset.classic<-estimateCommonDisp(dataset) 
  dataset.classic<-estimateTagwiseDisp(dataset.classic)  
  plotBCV(dataset.classic)
  summary(dataset.classic)
  
  # run the analyses    
  all.results<-tibble()
  for (sample.type in setdiff(samples,reference.sample)) {
    
    # compare each sample type against the specified reference type
    results<-exactTest(dataset.classic,pair=c(reference.sample,sample.type))
    # general information
    print(topTags(results))
    plotMD(results)
    
    # add data to annotations, calculate p.adj, update column names, and assign to object (dynamic)      
    tmp<-annotations%>%bind_cols(results$table)%>%
      mutate(!!paste0(sample.type,"__p.adj") :=p.adjust(PValue,"BH"),
             !!paste0(sample.type,"__p.value") :=PValue,
             !!paste0(sample.type,"__logFC") :=logFC)
    
    # combine all results into one table  
    if (nrow(all.results)==0){all.results<-tmp} else {all.results<-all.results%>%left_join(tmp,by = "guide.id")}
  }
  
  all.results<-all.results%>%select(guide.id,logCPM,starts_with("Atc"))
  
  # long results version for plotting
  all.results.long<-all.results%>%gather("key","value",-guide.id,-logCPM)%>%
    separate(key,c("sample","parameter"),sep="__")%>%
    spread(parameter,value)%>%
    separate(sample,c("atc.conc","strain","day"),sep="_") %>% 
    mutate(exp.id=select.exp.id)
  
  
  all.results.long%>%write_delim(paste0(outdir,"/output/",select.exp.id,"/CRISPRi_stat_exact_long_",select.exp.id,"_",select.strain,"_d",select.day,".tsv"),delim="\t")   
  
  
  
}


```


```{r import data}

# change the results directory 
ProjectDIR<-"<path/to/results/from/step2/>"



## set ggplot defaults

bcv.features<-100


# list all runs for analyses, change this for new data

migs.runs<-c("5440b")


dir.create(file.path(paste0(ProjectDIR,"Results/output/")),showWarnings = FALSE)


# read in the gRNA metadata
metadata.grna<-read_csv("Documents/summary_guide_data.csv")    

# load experiment ID details
library_tracker<-read_csv("Documents/CRISPRi_Library_Tracker.csv")

data.all1<-tibble()

for (migs.run in migs.runs){
  
  print(migs.run)

  # read in the processed read data
  data.in<-read_delim(paste0(ProjectDIR,"data_long_",migs.run,".tsv"),delim="\t",col_names=T,guess_max = 200000,
                      col_types = cols(
                        target.gene = col_character(),
                        guide.sequence = col_character(),
                        guide.length = col_double(),
                        guide.count.twist = col_double(),
                        pam = col_double(),
                        strength = col_double(),
                        v.index = col_double(),
                        ess.crispr = col_character(),
                        ess.tnseq = col_character(),
                        name.vi = col_character(),
                        product = col_character(),
                        guide.strand = col_character(),
                        guide.position = col_double(),
                        guide.gene.number = col_character(),
                        guide.id = col_character(),
                        guide.tag = col_character(),
                        sample = col_character(),
                        reads = col_double(),
                        sample.name = col_character(),
                        replicate = col_double(),
                        day = col_double(),
                        strain = col_character(), # required to use "6206" as the strain name
                        exclude = col_double() # replicates lost e.g. due to issues with the sample prep 
                        ))
  if (!("exp.id"%in%colnames(data.in))) {
    data.in$exp.id<-library_tracker$Experiment[match(migs.run,library_tracker$SeqID)]
  }
  if (length(unique(is.na(data.in$strain)))>1) {
    data.in<-subset(data.in,!is.na(data.in$strain))
    
  }
  data.all1<-data.all1%>%bind_rows(data.in)

}  


# quick check of what we have
data.all1%>%group_by(strain,day,exp.id) %>% tally() %>% print(n=36)



#### Before running below, make sure the output directory and subdirectories (as follows) exist, create one if not ####
## <outdir>/output/<select.exp.id>


# Run relevant analyses from below
# 
# ex07
run_analysis("6206",5,"Atc-0.00","ex07",ProjectDIR)
run_analysis("6206",10,"Atc-0.00","ex07",ProjectDIR)
run_analysis("6206",14,"Atc-0.00","ex07",ProjectDIR)

run_analysis("LZD-2",5,"Atc-0.00","ex07",ProjectDIR)
run_analysis("LZD-2",10,"Atc-0.00","ex07",ProjectDIR)
run_analysis("LZD-2",14,"Atc-0.00","ex07",ProjectDIR)

run_analysis("LEV-11",5,"Atc-0.00","ex07",ProjectDIR)
run_analysis("LEV-11",10,"Atc-0.00","ex07",ProjectDIR)
run_analysis("LEV-11",14,"Atc-0.00","ex07",ProjectDIR)

# ex08

run_analysis("RIF-1",5,"Atc-0.00","ex08",ProjectDIR)
run_analysis("RIF-1",10,"Atc-0.00","ex08",ProjectDIR)
run_analysis("RIF-1",14,"Atc-0.00","ex08",ProjectDIR) 

run_analysis("6206",5,"Atc-0.00","ex08",ProjectDIR)
run_analysis("6206",10,"Atc-0.00","ex08",ProjectDIR)  
run_analysis("6206",14,"Atc-0.00","ex08",ProjectDIR)

# ex09
run_analysis("6206",5,"Atc-0.00","ex09",ProjectDIR)
run_analysis("6206",10,"Atc-0.00","ex09",ProjectDIR)  
run_analysis("6206",14,"Atc-0.00","ex09",ProjectDIR) 

run_analysis("BDQ-2",5,"Atc-0.00","ex09",ProjectDIR)
run_analysis("BDQ-2",10,"Atc-0.00","ex09",ProjectDIR)  
run_analysis("BDQ-2",14,"Atc-0.00","ex09",ProjectDIR)

run_analysis("BDQ-14",5,"Atc-0.00","ex09",ProjectDIR)
run_analysis("BDQ-14",10,"Atc-0.00","ex09",ProjectDIR)  
run_analysis("BDQ-14",14,"Atc-0.00","ex09",ProjectDIR)

# change information from brackets to adjust to your own data

```